version: '3.9'

services:
  
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: recom
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: recommendationgames
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  api-recommendationgames:
    build:
      context: .
      dockerfile: RM.Presentation/Dockerfile
    container_name: api-recommendationgames
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - USER_DATABASE=Server=postgres-db;Port=5432;Database=recommendationgames;User ID=recom;Password=abc123
    ports:
      - "8090:8080"

volumes:
  postgres-data: