services:
  
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  api-recommendationgames:
    image: app-api-recommendationgames:1.2.1
    build:
      context: .
      dockerfile: .
    container_name: api-recommendationgames
    depends_on:
      - postgres-db
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080;
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8081
    ports:
      - "8080:8080"
      - "8081:8081"

volumes:
  postgres-data: