version: '3.9'

services:
  
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: recom
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: recommendationgames
    ports:
      - "5433:5432"